language: go
sudo: false

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

notifications:
  email: false

before_install:
  - if [ "$TRAVIS_GO_VERSION" = "1.8" ]; then go get github.com/mattn/goveralls; fi
script:
  - if [ "$TRAVIS_GO_VERSION" = "1.8" ]; then $HOME/gopath/bin/goveralls -service=travis-ci -package="./..."; fi
