language: go
sudo: false

go:
  - 1.13
  - 1.14
  - 1.15
  - tip

notifications:
  email: false

before_install:
  - go test ./...
  - if [ "$TRAVIS_GO_VERSION" = "1.15" ]; then go get github.com/mattn/goveralls; fi
script:
  - go test ./...
  - if [ "$TRAVIS_GO_VERSION" = "1.15" ]; then $HOME/gopath/bin/goveralls -service=travis-ci -package="./..."; fi
